// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	service "go-poker-project/Botnaught/botnaught/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	HealthEndpoint endpoint.Endpoint
	ActionEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.BotnaughtService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		ActionEndpoint: MakeActionEndpoint(s),
		HealthEndpoint: MakeHealthEndpoint(s),
	}
	for _, m := range mdw["Health"] {
		eps.HealthEndpoint = m(eps.HealthEndpoint)
	}
	for _, m := range mdw["Action"] {
		eps.ActionEndpoint = m(eps.ActionEndpoint)
	}
	return eps
}
